# Generated by Django 3.1.1 on 2020-09-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200914_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
