# Generated by Django 3.1.1 on 2020-09-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20200923_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Place of picture'),
            preserve_default=False,
        ),
    ]
