# Generated by Django 3.1.1 on 2020-09-24 17:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20200924_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(default='', verbose_name='Long description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(default='', verbose_name='Short description'),
            preserve_default=False,
        ),
    ]
